### PR TITLE
feat: upgrade django and python to latest stable versions

### PR DESCRIPTION
**Pull request by rochecompaan**
This PR upgrades the Scaf template to the latest stable Django and Python versions.

Most importantly, I removed the pins in the *.in files to ensure that a newly generated project always has the latest Django version. This is not a cause for concern since running `make compile` after project creation will immediately pin all package versions. Additionally, this forces us to perform regular tests of Scaf-generated projects with the latest versions.

I tested the changes in the PR by creating a new project and verifying that both the frontend and backend sites work and that NextJS can make GraphQL queries against Django.

### CODE REVIEW

**Comment by calvinhp** [comment]
I think my only concern is that folks will now need to be aware that if they run subsequent `pip-tools compile` against the project they will bring in newer versions of these base deps. This will happen often as you add new deps to the project.

I wonder if there would be a way to post process the `.in` files and add a sane upper bound like `Django<5.1` if a pin was originally chosen like `Django==5.0.7`?

**Comment by rochecompaan** [comment]
In practice, pinned versions stay pinned for far too long. We've had Django 4.1 (the sane default back many years) pinned since 18 August 2022. Having unpinned versions forces you to move forward, and it should be a non-issue if we have good test coverage. The packages we depend on help to keep the version sane since they will limit the required versions to the ones they have been tested with. The project should decide to pin versions. Scaf shouldn't decide that for the project.

**Comment by calvinhp** [comment]
I can agree with that, we should highlight this as a major feature of scaf so that folks are very aware of the thoughtfulness that went into that decision

**Comment by rochecompaan** [comment]
Cool! I'll add the decision as a note to our main README.

**Pull request merged**
